ALTER TABLE users
    ADD COLUMN IF NOT EXISTS plan VARCHAR(50) DEFAULT 'Gratuito',
    ADD COLUMN IF NOT EXISTS timezone VARCHAR(100) DEFAULT 'America/Sao_Paulo',
    ADD COLUMN IF NOT EXISTS avatar_url TEXT,
    ADD COLUMN IF NOT EXISTS streak_in_days INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS goal_per_day INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS reminder_email BOOLEAN DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS reminder_push BOOLEAN DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS weekly_summary BOOLEAN DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS ai_suggestions BOOLEAN DEFAULT FALSE;

ALTER TABLE decks
    ADD COLUMN IF NOT EXISTS description TEXT,
    ADD COLUMN IF NOT EXISTS subject VARCHAR(255),
    ADD COLUMN IF NOT EXISTS tags TEXT[] DEFAULT '{}';

ALTER TABLE flashcards
    ADD COLUMN IF NOT EXISTS tags TEXT[] DEFAULT '{}',
    ADD COLUMN IF NOT EXISTS difficulty VARCHAR(50) DEFAULT 'medium' CHECK (difficulty IN ('easy', 'medium', 'hard')),
    ADD COLUMN IF NOT EXISTS source TEXT;

CREATE TABLE IF NOT EXISTS user_integrations (
    id VARCHAR(255) PRIMARY KEY,
    user_id VARCHAR(255) REFERENCES users(id),
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL,
    connected BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TRIGGER update_timestamp
BEFORE UPDATE ON user_integrations
FOR EACH ROW
EXECUTE PROCEDURE update_timestamp();
